title: Bambu Klipper Docs
description: Bambu Klipper Conversion Documentation
theme: just-the-docs
logo: "/images/ChazMakes_Logo_With_Text.png"
color_scheme: dark


aux_links:
  "GitHub":
    - "https://github.com/ChazLayyd/Bambu-Lab-Klipper-Conversion"
  "Discord":
    - "https://discord.gg/W6B5mBejuC"
  "Ko-Fi":
    -  "https://ko-fi.com/chazmakes"


callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: grey-lt
  tip:
    title: Tip
    color: green
